"""empty message

Revision ID: 20851e664ccb
Revises: c45c27aec939
Create Date: 2022-11-11 10:54:42.204119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20851e664ccb'
down_revision = 'c45c27aec939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('header', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'header')
    # ### end Alembic commands ###
