"""empty message

Revision ID: 5348c4138186
Revises: bb70488f61fc
Create Date: 2022-11-08 10:20:56.124705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5348c4138186'
down_revision = 'bb70488f61fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_list', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo_list', 'todo_projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_list', type_='foreignkey')
    op.drop_column('todo_list', 'project_id')
    # ### end Alembic commands ###
