"""Added bio to User

Revision ID: 617ae5aae3cf
Revises: 
Create Date: 2022-10-22 12:40:25.848570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617ae5aae3cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
